# Numpy library

In [1]:
my_list = [1,2,3]

In [88]:
import numpy as np

In [89]:
arr = np.array(my_list)

In [90]:
arr

array([1, 2, 3])

In [9]:
my_matrix = [[1,2,4],[4,6,7],[7,5,4]]

In [10]:
np.array(my_matrix)

array([[1, 2, 4],
       [4, 6, 7],
       [7, 5, 4]])

In [11]:
my_mat_3x2 = [[1,2],[2,3],[3,7]]

In [12]:
np.array(my_mat_3x2)


array([[1, 2],
       [2, 3],
       [3, 7]])

In [15]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.arange(0,19)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [21]:
np.zeros((3,100))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

In [22]:
np.linspace(0,10,20)

array([  0.        ,   0.52631579,   1.05263158,   1.57894737,
         2.10526316,   2.63157895,   3.15789474,   3.68421053,
         4.21052632,   4.73684211,   5.26315789,   5.78947368,
         6.31578947,   6.84210526,   7.36842105,   7.89473684,
         8.42105263,   8.94736842,   9.47368421,  10.        ])

 How to create an identity matrix? what is an identity matrix?

An identity matrix is a 2d square matrix with diagnols of 1 and remaining elements of the matrix are zeros.

In numpy you can create an identity matrix using eye method of numpy.

In [23]:
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [24]:
np.eye(3)


array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [25]:
np.random.rand(10)

array([ 0.53376894,  0.53896512,  0.19868849,  0.08097755,  0.94680681,
        0.98069787,  0.71437272,  0.68723805,  0.96076789,  0.9413288 ])

In [26]:
np.random.rand(5,5)

array([[ 0.70452141,  0.95030932,  0.45546956,  0.25093367,  0.28270479],
       [ 0.03573286,  0.71351929,  0.58090547,  0.57052509,  0.70193357],
       [ 0.34904148,  0.35198098,  0.06693211,  0.38859414,  0.27651869],
       [ 0.553776  ,  0.3433421 ,  0.04868952,  0.68648177,  0.63123112],
       [ 0.01085404,  0.79118743,  0.75624601,  0.8818139 ,  0.07025552]])

rand() - > provides a uniform distribution among a given range
randn() - > provides a normal/gaussian distribution among a given range

In [27]:
np.random.randn(4)



array([ 1.08505311,  1.31071177,  0.03960915,  1.98462727])

In [28]:
np.random.randint(1,100,10)

array([57, 69, 76, 90, 27, 48, 66, 84, 23, 17])

In [34]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
arr = np.arange(20).reshape(4,5)

In [36]:
arr = np.arange(20).reshape(4,5)

In [37]:
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [38]:
arr.max()

19

In [39]:
arr.argmax()

19

In [40]:
arr = np.arange(20)

In [41]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [42]:
arr.max()

19

In [43]:
arr.argmax()

19

In [44]:
rnarr = np.random.randint(0,50,10)

In [45]:
rnarr

array([14, 39, 30,  9, 17, 14,  4,  9,  0, 48])

In [47]:
rnarr.argmin()


8

In [48]:
 rnarr.shape
    

(10,)

In [49]:
rnarr.dtype

dtype('int32')

# Numpy Indexing

In [50]:
arr = np.arange(0,11)

In [51]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr[8]

8

# Numpy Array Slicing

In [53]:
arr[1:4]

array([1, 2, 3])

In [54]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [56]:
arr[:4]

array([0, 1, 2, 3])

In [91]:
#2d indexing

In [93]:
arr2d = np.arange(0,25).reshape(5,5)

In [94]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [97]:
#Lets get the sub matrix [ 
#                            7,8
#                           12,13
#       ]

In [99]:
arr2d[1:3,2:4]

array([[ 7,  8],
       [12, 13]])

In [57]:
#Conditional Selection?

In [58]:
arr = np.arange(1,11)

In [59]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr > 2

array([False, False,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)


# Numpy operations


In [62]:
arr1 = np.arange(1,11)

In [63]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
# adding arr1 + arr1 performs elementwise addition on the array

In [65]:
arr1+arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [66]:
#with different arrays

In [75]:
arr2 = np.arange(11,21)

In [76]:
arr2

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [72]:
arr1 + arr2

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [73]:
#multiplication

In [74]:
arr1*arr2

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [77]:
#exponentiation

In [78]:
arr1 ** 2


array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [79]:
#subtraction

In [80]:
arr2-arr1

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [81]:
#division

In [82]:
arr2/arr1

array([ 11.        ,   6.        ,   4.33333333,   3.5       ,
         3.        ,   2.66666667,   2.42857143,   2.25      ,
         2.11111111,   2.        ])

Universal Array Functions

In [83]:
np.sqrt(arr1)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ,  3.16227766])

In [84]:
np.exp(arr1)

array([  2.71828183e+00,   7.38905610e+00,   2.00855369e+01,
         5.45981500e+01,   1.48413159e+02,   4.03428793e+02,
         1.09663316e+03,   2.98095799e+03,   8.10308393e+03,
         2.20264658e+04])

In [85]:
np.max(arr1)

10

In [86]:
np.min(arr2)

11

In [87]:
np.sin(arr1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])